language: r
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y netcdf-bin
  - sudo apt-get install -y nco
  - sudo apt-get install -y netcdf-doc
  - sudo apt-get install -y libnetcdf-dev
  - sudo apt-get install -y libnetcdf6

r_packages:
- RNetCDF

env:
  global:
    - GITHUB_REPO: "NVE/FlomKart"
    - GITHUB_PAT_FlomKart

before_script:
  - chmod +x ./_deploy.sh

script:
  - ./_deploy.sh
